Repository apple/swift-certificates, pull requests merged in 2023-05, with the labels that each got.

#59 Certificate Signing Request
  NOTICE.txt
  Package.swift
  Sources/X509/CMakeLists.txt
  Sources/X509/CSR/CSRAttribute.swift
  Sources/X509/CSR/CSRAttributes.swift
  Sources/X509/CSR/CSRVersion.swift
  Sources/X509/CSR/CertificateSigningRequest.swift
  Sources/X509/CSR/CertificationRequestInfo.swift
  Sources/X509/CSR/ExtensionRequest.swift
  Sources/X509/CertificatePublicKey.swift
  Sources/X509/Error.swift
  Tests/X509Tests/CSR Vectors/cryptography/LICENSE.APACHE
  Tests/X509Tests/CSR Vectors/cryptography/bad-version.pem
  Tests/X509Tests/CSR Vectors/cryptography/basic_constraints.pem
  Tests/X509Tests/CSR Vectors/cryptography/challenge-invalid.der
  Tests/X509Tests/CSR Vectors/cryptography/challenge-multi-valued.der
  Tests/X509Tests/CSR Vectors/cryptography/challenge-unstructured.pem
  Tests/X509Tests/CSR Vectors/cryptography/challenge.pem
  Tests/X509Tests/CSR Vectors/cryptography/ec_sha256.der
  Tests/X509Tests/CSR Vectors/cryptography/ec_sha256.pem
  Tests/X509Tests/CSR Vectors/cryptography/freeipa-bad-critical.pem
  Tests/X509Tests/CSR Vectors/cryptography/invalid_signature.pem
  Tests/X509Tests/CSR Vectors/cryptography/long-form-attribute.pem
  Tests/X509Tests/CSR Vectors/cryptography/rsa_md4.der
  Tests/X509Tests/CSR Vectors/cryptography/rsa_md4.pem
  Tests/X509Tests/CSR Vectors/cryptography/rsa_sha1.der
  Tests/X509Tests/CSR Vectors/cryptography/rsa_sha1.pem
  Tests/X509Tests/CSR Vectors/cryptography/rsa_sha256.der
  Tests/X509Tests/CSR Vectors/cryptography/rsa_sha256.pem
  Tests/X509Tests/CSR Vectors/cryptography/san_rsa_sha1.der
  Tests/X509Tests/CSR Vectors/cryptography/san_rsa_sha1.pem
  Tests/X509Tests/CSR Vectors/cryptography/two_basic_constraints.pem
  Tests/X509Tests/CSR Vectors/cryptography/unsupported_extension.pem
  Tests/X509Tests/CSR Vectors/cryptography/unsupported_extension_critical.pem
  Tests/X509Tests/CSRTests.swift
Labels: 🔼 needs-minor-version-bump

#80 Gracefully fail `Extension` serialization
  Sources/X509/Extensions.swift
  Sources/X509/ExtensionsBuilder.swift
  Tests/X509Tests/ExtensionBuilderTests.swift
  Tests/X509Tests/OCSPPolicyVerifierTests.swift
Labels: 🔼 needs-minor-version-bump

#79 Policy Builder
  Sources/X509/CMakeLists.txt
  Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
  Sources/X509/OCSP/OCSPPolicy.swift
  Sources/X509/Verifier/AnyPolicy.swift
  Sources/X509/Verifier/PolicyBuilder.swift
  Sources/X509/Verifier/Verifier.swift
  Sources/X509/Verifier/VerifierPolicy.swift
  Tests/X509Tests/CMSTests.swift
  Tests/X509Tests/CertificateDERTests.swift
  Tests/X509Tests/PolicyBuilderTests.swift
  Tests/X509Tests/RFC5280PolicyTests.swift
  Tests/X509Tests/VerifierTests.swift
Labels: 🔼 needs-minor-version-bump

#81 Fix OCSP serialisation and parsing tests
  Sources/X509/OCSP/OCSPSingleResponse.swift
  Tests/X509Tests/OCSPTests.swift
Labels: needs-no-version-bump

#82 Actually validate we can parse the signature.
  Tests/X509Tests/SignatureTests.swift
Labels: needs-no-version-bump

#83 [README] Add a leading dot to upToNextMinor
  README.md
Labels: needs-no-version-bump

#85 Make expiry checking cheaper.
  Package.swift
  Sources/X509/Verifier/RFC5280/ExpiryPolicy.swift
  Sources/X509/X509BaseTypes/Time.swift
  Tests/X509Tests/OCSPPolicyVerifierTests.swift
  Tests/X509Tests/OCSPTests.swift
Labels: patch-version-bump-only

#87 Don't rely on having a SEP present
  Tests/X509Tests/SignatureTests.swift
Labels: needs-no-version-bump

#86 Make constructing Dates cheaper
  NOTICE.txt
  Sources/X509/CMakeLists.txt
  Sources/X509/Certificate.swift
  Sources/X509/OCSP/OCSPPolicy.swift
  Sources/X509/X509BaseTypes/Time.swift
  Sources/X509/X509BaseTypes/TimeCalculations.swift
  Tests/X509Tests/OCSPPolicyVerifierTests.swift
  Tests/X509Tests/TimeTests.swift
Labels: needs-no-version-bump

#88 Remove the "from parts" Certificate constructor.
  Sources/X509/Certificate.swift
Labels: 🔼 needs-minor-version-bump
