Repository apple/swift-certificates, pull requests merged in 2023-08, with the labels that each got.

#115 Make `debugDescription` work well as part of a structural display
  Sources/X509/Verifier/VerificationDiagnostic.swift
Labels: patch-version-bump-only

#117 Use `Certificate.description` instead of `dump` for debugging flaky tests
  Tests/X509Tests/OCSPPolicyVerifierTests.swift
Labels: needs-no-version-bump

#118 Reject `v1` `Certificate`s with extensions
  Sources/X509/CMakeLists.txt
  Sources/X509/Verifier/RFC5280/RFC5280Policy.swift
  Sources/X509/Verifier/RFC5280/VersionPolicy.swift
  Tests/X509Tests/RFC5280PolicyTests.swift
Labels: patch-version-bump-only

#119 Do not count self-issued certificates against maxPathLength
  Sources/X509/Verifier/RFC5280/BasicConstraintsPolicy.swift
  Tests/X509Tests/RFC5280PolicyTests.swift
Labels: patch-version-bump-only

#122 Allow `RelativeDistinguishedNameConvertible` to fail gracefully
  Sources/X509/DistinguishedName.swift
  Sources/X509/DistinguishedNameBuilder/DNBuilder.swift
  Tests/X509Tests/DistinguishedNameBuilderTests.swift
Labels: 🔼 needs-minor-version-bump

#124 Use valid `ASN1ObjectIdentifier` in tests with at least two components
  Tests/X509Tests/ExtendedKeyUsageTests.swift
  Tests/X509Tests/ExtensionBuilderTests.swift
  Tests/X509Tests/PolicyBuilderTests.swift
Labels: needs-no-version-bump

#123 Remove deprecated API
  Sources/X509/Verifier/AnyPolicy.swift
Labels: 🔼 needs-minor-version-bump

#126 Add `PolicyFailureReason` to support lazy failure reason string interpolation
  IntegrationTests/tests_01_allocation_counters/test_01_resources/test_validation.swift
  Sources/X509/OCSP/OCSPPolicy.swift
  Sources/X509/Verifier/RFC5280/BasicConstraintsPolicy.swift
  Sources/X509/Verifier/VerificationDiagnostic.swift
  Sources/X509/Verifier/Verifier.swift
  Sources/X509/Verifier/VerifierPolicy.swift
  Tests/X509Tests/VerifierTests.swift
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: 🔼 needs-minor-version-bump

#128 Refactor `ASN1UTF8StringView` to `ASN1TaggedStringView` and use it for `printable` strings
  Sources/X509/RDNAttribute.swift
Labels: patch-version-bump-only

#127 Fix preference of root certificates
  Sources/X509/Verifier/Verifier.swift
  Tests/X509Tests/VerifierTests.swift
Labels: patch-version-bump-only

#129 Make PublicKey DERImplicitlyTaggable
  Sources/X509/CertificatePublicKey.swift
Labels: 🔼 needs-minor-version-bump

#131 Use beta release of `swift-asn1`
  IntegrationTests/tests_01_allocation_counters/test_01_resources/run-swift-certificates-alloc-counter-tests.sh
  Package.swift
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: 🔼 needs-minor-version-bump

#132 Add `Certificate.PrivateKey` description
  Sources/X509/CertificatePrivateKey.swift
  Sources/X509/CertificatePublicKey.swift
  Tests/X509Tests/CertificateTests.swift
Labels: patch-version-bump-only
