Repository apple/swift-certificates, pull requests merged in 2023-06, with the labels that each got.

#89 Remove unnecessary TODO
  Sources/X509/Signature.swift
Labels: needs-no-version-bump

#92 Implement remove for `RelativeDistinguishedName`
  Sources/X509/RelativeDistinguishedName.swift
  Tests/X509Tests/DistinguishedNameTests.swift
Labels: 🔼 needs-minor-version-bump

#93 We aren't supporting PSS for now.
  Sources/X509/CertificatePublicKey.swift
  Sources/X509/X509BaseTypes/AlgorithmIdentifier.swift
Labels: patch-version-bump-only

#95 Limit the number elements in `Extensions` and `ExtendedKeyUsage`
  Sources/X509/Extension Types/ExtendedKeyUsage.swift
  Sources/X509/Extensions.swift
  Tests/X509Tests/ExtendedKeyUsageTests.swift
  Tests/X509Tests/ExtensionBuilderTests.swift
Labels: patch-version-bump-only

#96 Setup allocation test framework
  IntegrationTests/plugin_echo.sh
  IntegrationTests/plugin_junit_xml.sh
  IntegrationTests/run-single-test.sh
  IntegrationTests/run-tests.sh
  IntegrationTests/test_functions.sh
  IntegrationTests/tests_01_allocation_counters/defines.sh
  IntegrationTests/tests_01_allocation_counters/test_01_allocation_counts.sh
  IntegrationTests/tests_01_allocation_counters/test_01_resources/run-swift-certificates-alloc-counter-tests.sh
  IntegrationTests/tests_01_allocation_counters/test_01_resources/shared.swift
  IntegrationTests/tests_01_allocation_counters/test_01_resources/test_empty_1.swift
  NOTICE.txt
  dev/alloc-limits-from-test-output
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
  docker/docker-compose.yaml
  scripts/integration_tests.sh
Labels: needs-no-version-bump

#94 Implement property setters of `NameConstraints`
  Sources/X509/Extension Types/NameConstraints.swift
  Tests/X509Tests/NameConstraintsTests.swift
Labels: 🔼 needs-minor-version-bump

#100 Added subjectPublicKeyInfoBytes to public keys
  Sources/X509/CertificatePublicKey.swift
  Sources/X509/Extension Types/SubjectKeyIdentifier.swift
  Sources/X509/OCSP/OCSPPolicy.swift
  Tests/X509Tests/CertificateTests.swift
Labels: 🔼 needs-minor-version-bump

#97 Add allocation test that parses all WebPKI roots
  IntegrationTests/tests_01_allocation_counters/test_01_resources/shared.swift
  IntegrationTests/tests_01_allocation_counters/test_01_resources/test_parse_webpki_roots.swift
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: needs-no-version-bump

#105 Conform `AuthorityInformationAccess` to `RangeReplaceableCollection`
  Sources/X509/Extension Types/AuthorityInformationAccess.swift
  Sources/X509/Extension Types/ExtendedKeyUsage.swift
  Tests/X509Tests/CertificateTests.swift
Labels: 🔼 needs-minor-version-bump

#106 Add integer initialisers on `Certificate.SerialNumber`
  Sources/X509/CertificateSerialNumber.swift
  Sources/X509/X509BaseTypes/ECDSASignature.swift
  Tests/X509Tests/CertificateTests.swift
Labels: 🔼 needs-minor-version-bump
