Repository apple/swift-certificates, pull requests merged in 2023-04, with the labels that each got.

#55 Add support for using SecureEnclave.P256
  Sources/X509/CertificatePrivateKey.swift
  Sources/X509/Digests.swift
  Tests/X509Tests/SignatureTests.swift
Labels: 🔼 needs-minor-version-bump

#56 Documentation - Typos
  Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
  Sources/X509/DistinguishedName.swift
  Sources/X509/Extension Types/ExtensionIdentifiers.swift
  Sources/X509/Extension Types/NameConstraints.swift
  Sources/X509/Verifier/RFC5280/RFC5280Policy.swift
  Sources/X509/Verifier/Verifier.swift
Labels: needs-no-version-bump

#60 Add support for unwrapping public keys.
  Sources/X509/CertificatePublicKey.swift
  Tests/X509Tests/CertificateTests.swift
Labels: 🔼 needs-minor-version-bump

#61 OCSP soft failure mode
  Sources/X509/OCSP/OCSPPolicy.swift
  Tests/X509Tests/OCSPPolicyVerifierTests.swift
Labels: 🔼 needs-minor-version-bump

#62 Fix `Sendable` warning in `OCSPVerifierPolicy. self.chainMeetsPolicyRequirementsWithoutDeadline`
  Sources/X509/OCSP/OCSPPolicy.swift
Labels: patch-version-bump-only

#65 Expose a CMSSignature type
  Sources/X509/CMakeLists.txt
  Sources/X509/CryptographicMessageSyntax/CMSContentInfo.swift
  Sources/X509/CryptographicMessageSyntax/CMSEncapsulatedContentInfo.swift
  Sources/X509/CryptographicMessageSyntax/CMSIssuerAndSerialNumber.swift
  Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
  Sources/X509/CryptographicMessageSyntax/CMSSignature.swift
  Sources/X509/CryptographicMessageSyntax/CMSSignedData.swift
  Sources/X509/CryptographicMessageSyntax/CMSSignerIdentifier.swift
  Sources/X509/CryptographicMessageSyntax/CMSSignerInfo.swift
  Sources/X509/CryptographicMessageSyntax/CMSVersion.swift
  Tests/X509Tests/CMSTests.swift
Labels: patch-version-bump-only

#67 Exclude Secure Enclave related code from CMake build
  CMakeLists.txt
  Package.swift
  Sources/X509/CertificatePrivateKey.swift
  Sources/X509/Digests.swift
Labels: needs-no-version-bump

#68 Proper fix for 'SecureEnclave' issue in cmake build
  CMakeLists.txt
  Package.swift
  Sources/X509/CertificatePrivateKey.swift
  Sources/X509/Digests.swift
Labels: 🔼 needs-minor-version-bump

#69 Clean up the upToNextMinor
  README.md
Labels: needs-no-version-bump

#72 X509: make the code more portable
  Sources/X509/Verifier/RFC5280/URIConstraints.swift
Labels: patch-version-bump-only

#75 Fixed referenced property name in documentation
  Sources/X509/Docs.docc/Creating Certificates.md
Labels: needs-no-version-bump

#71 Support PEM serialisation and parsing of `Certificate`, `Certificate.PublicKey` and `Certificate.PrivateKey`
  NOTICE.txt
  Package.swift
  Sources/X509/CMakeLists.txt
  Sources/X509/Certificate.swift
  Sources/X509/CertificatePrivateKey.swift
  Sources/X509/CertificatePublicKey.swift
  Sources/X509/Error.swift
  Sources/X509/PKCS8PrivateKey.swift
  Sources/X509/SEC1PrivateKey.swift
  Sources/X509/X509BaseTypes/AlgorithmIdentifier.swift
  Tests/X509Tests/PEMTestRSACertificate.pem
  Tests/X509Tests/PEMTests.swift
  rsakey.pem
Labels: 🔼 needs-minor-version-bump
