Repository apple/swift-certificates, pull requests merged in 2023-12, with the labels that each got.

#154 Support converting RDNAttribute values into Strings
  Sources/X509/RDNAttribute.swift
  Tests/X509Tests/DistinguishedNameTests.swift
Labels: 🔼 needs-minor-version-bump

#153 build: support building in Debug mode on Windows
  CMakeLists.txt
Labels: needs-no-version-bump

#157 Move `ExpressibleByArrayLiteral` conformance of `_TinyArray` to the declaring module
  Sources/X509/CryptographicMessageSyntax/CMSSignature.swift
  Sources/X509/OCSP/OCSPPolicy.swift
  Sources/_CertificateInternals/_TinyArray.swift
  Tests/CertificateInternalsTests/TinyArrayTests.swift
  Tests/X509Tests/OCSPPolicyVerifierTests.swift
Labels: 🔼 needs-minor-version-bump

#156 Simplify the internal representation of `RDN.Attribute.Value`
  Sources/X509/RDNAttribute.swift
  Tests/X509Tests/DistinguishedNameTests.swift
Labels: patch-version-bump-only

#159 Add missing availability guards in tests
  Tests/X509Tests/CertificateTests.swift
  Tests/X509Tests/OCSPPolicyVerifierTests.swift
  Tests/X509Tests/PEMTests.swift
  Tests/X509Tests/VerifierTests.swift
Labels: needs-no-version-bump
