Repository apple/swift-certificates, pull requests merged in 2024-03, with the labels that each got.

#164 Raise minimum Swift version to 5.8
  Benchmarks/Package.swift
  Benchmarks/Thresholds/5.7/CertificatesBenchmark.Parse_WebPKI_Roots_from_DER.p90.json
  Benchmarks/Thresholds/5.7/CertificatesBenchmark.Parse_WebPKI_Roots_from_PEM_files.p90.json
  Benchmarks/Thresholds/5.7/CertificatesBenchmark.Parse_WebPKI_Roots_from_multi_PEM_file.p90.json
  Benchmarks/Thresholds/5.7/CertificatesBenchmark.TinyArray.append.p90.json
  Benchmarks/Thresholds/5.7/CertificatesBenchmark.TinyArray_non-allocating_functions.p90.json
  Benchmarks/Thresholds/5.7/CertificatesBenchmark.Verifier.p90.json
  Package.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.57.yaml
Labels: 🔼 needs-minor-version-bump

#165 CountryName should be a PrintableString RDNA
  Sources/X509/DistinguishedNameBuilder/CountryName.swift
  Tests/X509Tests/DistinguishedNameBuilderTests.swift
  Tests/X509Tests/DistinguishedNameTests.swift
Labels: patch-version-bump-only

#166 Fix `Sendable` warnings from latest `main` compiler
  Sources/X509/CertificatePrivateKey.swift
  Sources/X509/CertificatePublicKey.swift
  Sources/X509/Error.swift
  Sources/X509/OCSP/OCSPPolicy.swift
  Sources/X509/PromiseAndFuture.swift
  Sources/X509/Signature.swift
Labels: patch-version-bump-only

#167 Remove now-breaking test vector test
  Tests/X509Tests/CSRTests.swift
Labels: needs-no-version-bump
