Repository apple/swift-certificates, pull requests merged in 2024-11, with the labels that each got.

#207 Android build fixes
  Sources/X509/Verifier/ServerIdentityPolicy.swift
Labels: semver/patch

#208 unify scheduled and main yamls
  .github/workflows/main.yml
  .github/workflows/scheduled.yml
Labels: semver/none

#206 Add support for attached signatures (#201)
  Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
  Tests/X509Tests/CMSTests.swift
Labels: semver/minor

#210 Aligning semantic version label check name
  .github/workflows/pull_request_label.yml
Labels: semver/none
