Repository apple/swift-certificates, pull requests merged in 2024-08, with the labels that each got.

#189 Up our scaling factor to kilo
  Benchmarks/Benchmarks/CertificatesBenchmark/Benchmarks.swift
  Benchmarks/Thresholds/5.10/CertificatesBenchmark.Parse_WebPKI_Roots_from_DER.p90.json
  Benchmarks/Thresholds/5.10/CertificatesBenchmark.Parse_WebPKI_Roots_from_PEM_files.p90.json
  Benchmarks/Thresholds/5.10/CertificatesBenchmark.Parse_WebPKI_Roots_from_multi_PEM_file.p90.json
  Benchmarks/Thresholds/5.10/CertificatesBenchmark.TinyArray.append.p90.json
  Benchmarks/Thresholds/5.10/CertificatesBenchmark.TinyArray_non-allocating_functions.p90.json
  Benchmarks/Thresholds/5.10/CertificatesBenchmark.Verifier.p90.json
  Benchmarks/Thresholds/5.8/CertificatesBenchmark.Parse_WebPKI_Roots_from_DER.p90.json
  Benchmarks/Thresholds/5.8/CertificatesBenchmark.Parse_WebPKI_Roots_from_PEM_files.p90.json
  Benchmarks/Thresholds/5.8/CertificatesBenchmark.Parse_WebPKI_Roots_from_multi_PEM_file.p90.json
  Benchmarks/Thresholds/5.8/CertificatesBenchmark.TinyArray.append.p90.json
  Benchmarks/Thresholds/5.8/CertificatesBenchmark.TinyArray_non-allocating_functions.p90.json
  Benchmarks/Thresholds/5.8/CertificatesBenchmark.Verifier.p90.json
  Benchmarks/Thresholds/5.9/CertificatesBenchmark.Parse_WebPKI_Roots_from_DER.p90.json
  Benchmarks/Thresholds/5.9/CertificatesBenchmark.Parse_WebPKI_Roots_from_PEM_files.p90.json
  Benchmarks/Thresholds/5.9/CertificatesBenchmark.Parse_WebPKI_Roots_from_multi_PEM_file.p90.json
  Benchmarks/Thresholds/5.9/CertificatesBenchmark.TinyArray.append.p90.json
  Benchmarks/Thresholds/5.9/CertificatesBenchmark.TinyArray_non-allocating_functions.p90.json
  Benchmarks/Thresholds/5.9/CertificatesBenchmark.Verifier.p90.json
Labels: needs-no-version-bump

#188 Stop implicitly tagging DistinguishedName
  Sources/X509/CSR/CertificationRequestInfo.swift
  Sources/X509/CryptographicMessageSyntax/CMSIssuerAndSerialNumber.swift
  Sources/X509/DistinguishedName.swift
  Sources/X509/GeneralName.swift
  Sources/X509/X509BaseTypes/TBSCertificate.swift
  Tests/X509Tests/CertificateTests.swift
Labels: 🔼 needs-minor-version-bump

#185 Use filePath for test assert location
  Tests/X509Tests/CMSTests.swift
  Tests/X509Tests/OCSPPolicyVerifierTests.swift
  Tests/X509Tests/ServerIdentityPolicyTests.swift
Labels: needs-no-version-bump

#187 Import crypto with preconcurrency flag
  Tests/X509Tests/OCSPPolicyVerifierTests.swift
  Tests/X509Tests/PolicyBuilderTests.swift
  Tests/X509Tests/RFC5280PolicyTests.swift
  Tests/X509Tests/SignatureTests.swift
  Tests/X509Tests/VerifierTests.swift
Labels: patch-version-bump-only
