Repository apple/swift-certificates, pull requests merged in 2025-07, with the labels that each got.

#257 Support singing via Certificate PrivateKey
  Sources/X509/CertificatePrivateKey.swift
  Sources/X509/Signature.swift
  Tests/X509Tests/SignatureTests.swift
Labels: 🆕 semver/minor

#259 Skip errors relating to interaction not being allowed
  Tests/X509Tests/SecKeyWrapperTests.swift
Labels: semver/none

#262 [1.10.x] Fix pthread use on FreeBSD (#253)
  Sources/X509/Lock.swift
Labels: 🔨 semver/patch

#270 Enable release mode builds
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none
