Repository apple/swift-certificates, pull requests merged in 2025-01, with the labels that each got.

#217 Add Android import for IPAddressNameTests
  Tests/X509Tests/IPAddressTests.swift
Labels: 🔨 semver/patch

#218 Tag CMS signer identifier implicitly
  Sources/X509/CryptographicMessageSyntax/CMSSignerIdentifier.swift
  Tests/X509Tests/CMSTests.swift
Labels: 🔨 semver/patch

#219 Use proper hash when computing message digest in signed attributes
  Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
  Sources/X509/Digests.swift
  Tests/X509Tests/CMSTests.swift
Labels: 🔨 semver/patch

#222 Fix a small error in AlgorithmIdentifier description and add missing cases
  Sources/X509/X509BaseTypes/AlgorithmIdentifier.swift
Labels: 🔨 semver/patch

#223 fix amd64 support
  cmake/modules/SwiftSupport.cmake
Labels: 🔨 semver/patch

#224 Move nightly-6.0 benchmark thresholds to 6.1
  Benchmarks/Thresholds/nightly-6.1/CertificatesBenchmark.Parse_WebPKI_Roots_from_DER.p90.json
  Benchmarks/Thresholds/nightly-6.1/CertificatesBenchmark.Parse_WebPKI_Roots_from_PEM_files.p90.json
  Benchmarks/Thresholds/nightly-6.1/CertificatesBenchmark.Parse_WebPKI_Roots_from_multi_PEM_file.p90.json
  Benchmarks/Thresholds/nightly-6.1/CertificatesBenchmark.TinyArray.append.p90.json
  Benchmarks/Thresholds/nightly-6.1/CertificatesBenchmark.TinyArray_non-allocating_functions.p90.json
  Benchmarks/Thresholds/nightly-6.1/CertificatesBenchmark.Verifier.p90.json
Labels: semver/none

#221 Add default value for signature algorithm
  Sources/X509/CSR/CertificateSigningRequest.swift
  Sources/X509/Certificate.swift
  Sources/X509/CertificatePrivateKey.swift
  Sources/X509/CertificatePublicKey.swift
  Sources/X509/CryptographicMessageSyntax/CMSOperations.swift
  Sources/X509/Digests.swift
  Sources/X509/SecKeyWrapper.swift
  Sources/X509/Signature.swift
  Sources/X509/SignatureAlgorithm.swift
  Tests/X509Tests/CMSTests.swift
  Tests/X509Tests/CSRTests.swift
  Tests/X509Tests/CertificateTests.swift
Labels: 🆕 semver/minor

#225 CI use 6.1 nightlies
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none
